-- admin 추가
insert into user_account(user_id, password, role_type, email, nickname, memo, created_at, modified_at)
values ('admin', '$2a$10$MRoAwXIsWzYskEaj1U9lOOoM84B6EPoR.yj5tQyR72iSgVp2HayG6', 'ADMIN', 'admin@email.com', 'admin', null, now(), now()),
       ('tester', '$2a$10$hIDJIM6ab.OoT07Ub5a0ve7pAlgG3EbHBNGJy69ewtPrV5e6BZLIa', 'USER', 'tester@email.com', 'tester', null, now(), now()),
       ('tester2', '$2a$10$hIDJIM6ab.OoT07Ub5a0ve7pAlgG3EbHBNGJy69ewtPrV5e6BZLIa', 'USER', 'tester@email.com', 'tester', null, now(), now());

-- 공지사항
insert into notice_board(id, user_id, title, content, created_by, created_at, modified_by, modified_at)
values (1, 'admin', 'title1', 'content1', 'admin', now() - interval '23 day', 'admin', now() - interval '23 day'),
       (2, 'admin', 'title2', 'content2', 'admin', now() - interval '22 day', 'admin', now() - interval '22 day'),
       (3, 'admin', 'title3', 'content3', 'admin', now() - interval '21 day', 'admin', now() - interval '21 day'),
       (4, 'admin', 'title4', 'content4', 'admin', now() - interval '20 day', 'admin', now() - interval '20 day'),
       (5, 'admin', 'title5', 'content5', 'admin', now() - interval '19 day', 'admin', now() - interval '19 day'),
       (6, 'admin', 'title6', 'content6', 'admin', now() - interval '18 day', 'admin', now() - interval '18 day'),
       (7, 'admin', 'title7', 'content7', 'admin', now() - interval '17 day', 'admin', now() - interval '17 day'),
       (8, 'admin', 'title8', 'content8', 'admin', now() - interval '16 day', 'admin', now() - interval '16 day'),
       (9, 'admin', 'title9', 'content9', 'admin', now() - interval '15 day', 'admin', now() - interval '15 day'),
       (10, 'admin', 'title10', 'content10', 'admin', now() - interval '14 day', 'admin', now() - interval '14 day'),
       (11, 'admin', 'title11', 'content11', 'admin', now() - interval '13 day', 'admin', now() - interval '13 day'),
       (12, 'admin', 'title12', 'content12', 'admin', now() - interval '12 day', 'admin', now() - interval '12 day'),
       (13, 'admin', 'title13', 'content13', 'admin', now() - interval '11 day', 'admin', now() - interval '11 day'),
       (14, 'admin', 'title14', 'content14', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       (15, 'admin', 'title15', 'content15', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       (16, 'admin', 'title16', 'content16', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       (17, 'admin', 'title17', 'content17', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       (18, 'admin', 'title18', 'content18', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       (19, 'admin', 'title19', 'content19', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (20, 'admin', 'title20', 'content20', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (21, 'admin', 'title21', 'content21', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (22, 'admin', 'title22', 'content22', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (23, 'admin', 'title23', 'content23', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (24, 'admin', 'title23', 'content23', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       (25, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (26, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (27, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (28, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (29, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (30, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (31, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (32, 'admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       (33, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (34, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (35, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (36, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (37, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (38, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (39, 'admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       (40, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (41, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (42, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (43, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (44, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (45, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (46, 'admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       (47, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (48, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (49, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (50, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (51, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (52, 'admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       (53, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (54, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (55, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (56, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (57, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (58, 'admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       (59, 'admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       (60, 'admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       (61, 'admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       (62, 'admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       (63, 'admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       (64, 'admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       (65, 'admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       (66, 'admin', 'title24', 'content24', 'admin', now(), 'admin', now());

-- 질문 게시판
insert into question_board(id, user_id, title, content, tag, view_count, created_by, created_at, modified_by, modified_at)
values (1, 'tester', 'question title', 'content', null, 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       (2, 'tester', 'question title2', 'content2', null, 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       (3, 'tester', 'question title3', 'content3', null, 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       (4, 'tester', 'question title4', 'content4', null, 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       (5, 'tester', 'question title5', 'content5', null, 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       (6, 'tester', 'question title6', 'content6', null, 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       (7, 'tester', 'question title7', 'content7', null, 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       (8, 'tester', 'question title8', 'content8', null, 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       (9, 'tester', 'question title9', 'content9', null, 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       (10, 'tester', 'question title10', 'content10', null, 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       (11, 'tester', 'question title11', 'content11', null, 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       (12, 'tester', 'question title12', 'content12', null, 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       (13, 'tester', 'question title13', 'content13', null, 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       (14, 'tester', 'question title14', 'content14', null, 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       (15, 'tester', 'question title15', 'content15', null, 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       (16, 'tester', 'question title16', 'content16', null, 0, 'tester', now() - interval '8 day', 'tester', now() - interval '8 day'),
       (17, 'tester', 'question title17', 'content17', null, 0, 'tester', now() - interval '7 day', 'tester', now() - interval '7 day'),
       (18, 'tester', 'question title18', 'content18', null, 0, 'tester', now() - interval '6 day', 'tester', now() - interval '6 day'),
       (19, 'tester', 'question title19', 'content19', null, 0, 'tester', now() - interval '5 day', 'tester', now() - interval '5 day'),
       (20, 'tester', 'question title20', 'content20', null, 0, 'tester', now() - interval '4 day', 'tester', now() - interval '4 day'),
       (21, 'tester', 'question title21', 'content21', null, 0, 'tester', now() - interval '3 day', 'tester', now() - interval '3 day'),
       (22, 'tester', 'question title22', 'content22', null, 0, 'tester', now() - interval '2 day', 'tester', now() - interval '2 day'),
       (23, 'tester', 'question title23', 'content23', null, 0, 'tester', now() - interval '1 day', 'tester', now() - interval '1 day'),
       (24, 'tester', 'question title24', 'content content content content content content content content content content content content', null, 0, 'tester', now(), 'tester', now());
