-- admin 추가
insert into user_account(user_id, password, role_type, email, nickname, memo, created_at, modified_at)
values ('admin', '$2a$10$MRoAwXIsWzYskEaj1U9lOOoM84B6EPoR.yj5tQyR72iSgVp2HayG6', 'ADMIN', 'admin@email.com', 'admin', null, now(), now()),
       ('tester', '$2a$10$hIDJIM6ab.OoT07Ub5a0ve7pAlgG3EbHBNGJy69ewtPrV5e6BZLIa', 'USER', 'tester@email.com', 'tester', null, now(), now()),
       ('tester2', '$2a$10$hIDJIM6ab.OoT07Ub5a0ve7pAlgG3EbHBNGJy69ewtPrV5e6BZLIa', 'USER', 'tester@email.com', 'tester', null, now(), now());

-- 공지사항
insert into notice_board(user_id, title, content, created_by, created_at, modified_by, modified_at)
values ('admin', 'title1', 'content1', 'admin', now() - interval '23 day', 'admin', now() - interval '23 day'),
       ('admin', 'title2', 'content2', 'admin', now() - interval '22 day', 'admin', now() - interval '22 day'),
       ('admin', 'title3', 'content3', 'admin', now() - interval '21 day', 'admin', now() - interval '21 day'),
       ('admin', 'title4', 'content4', 'admin', now() - interval '20 day', 'admin', now() - interval '20 day'),
       ('admin', 'title5', 'content5', 'admin', now() - interval '19 day', 'admin', now() - interval '19 day'),
       ('admin', 'title6', 'content6', 'admin', now() - interval '18 day', 'admin', now() - interval '18 day'),
       ('admin', 'title7', 'content7', 'admin', now() - interval '17 day', 'admin', now() - interval '17 day'),
       ('admin', 'title8', 'content8', 'admin', now() - interval '16 day', 'admin', now() - interval '16 day'),
       ('admin', 'title9', 'content9', 'admin', now() - interval '15 day', 'admin', now() - interval '15 day'),
       ('admin', 'title10', 'content10', 'admin', now() - interval '14 day', 'admin', now() - interval '14 day'),
       ('admin', 'title11', 'content11', 'admin', now() - interval '13 day', 'admin', now() - interval '13 day'),
       ('admin', 'title12', 'content12', 'admin', now() - interval '12 day', 'admin', now() - interval '12 day'),
       ('admin', 'title13', 'content13', 'admin', now() - interval '11 day', 'admin', now() - interval '11 day'),
       ('admin', 'title14', 'content14', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       ('admin', 'title15', 'content15', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       ('admin', 'title16', 'content16', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       ('admin', 'title17', 'content17', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       ('admin', 'title18', 'content18', 'admin', now() - interval '10 day', 'admin', now() - interval '10 day'),
       ('admin', 'title19', 'content19', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title20', 'content20', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title21', 'content21', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title22', 'content22', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '9 day', 'admin', now() - interval '9 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '8 day', 'admin', now() - interval '8 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '7 day', 'admin', now() - interval '7 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '6 day', 'admin', now() - interval '6 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '5 day', 'admin', now() - interval '5 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '4 day', 'admin', now() - interval '4 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '3 day', 'admin', now() - interval '3 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       ('admin', 'title23', 'content23', 'admin', now() - interval '2 day', 'admin', now() - interval '2 day'),
       ('admin', 'title24', 'content24', 'admin', now(), 'admin', now());

-- 질문 게시판
insert into question_board(user_id, title, content, tag, view_count, created_by, created_at, modified_by, modified_at)
values ('tester', 'question title', 'content', 'Free', 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       ('tester', 'question title2', 'content2', 'Free', 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       ('tester', 'question title3', 'content3', 'Free', 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       ('tester', 'question title4', 'content4', 'Free', 0, 'tester', now() - interval '12 day', 'tester', now() - interval '12 day'),
       ('tester', 'question title5', 'content5', 'Free', 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       ('tester', 'question title6', 'content6', 'Free', 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       ('tester', 'question title7', 'content7', 'Free', 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       ('tester', 'question title8', 'content8', 'Free', 0, 'tester', now() - interval '11 day', 'tester', now() - interval '11 day'),
       ('tester', 'question title9', 'content9', 'Free', 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       ('tester', 'question title10', 'content10', 'Free', 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       ('tester', 'question title11', 'content11', 'Free', 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       ('tester', 'question title12', 'content12', 'Free', 0, 'tester', now() - interval '10 day', 'tester', now() - interval '10 day'),
       ('tester', 'question title13', 'content13', 'Free', 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       ('tester', 'question title14', 'content14', 'English', 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       ('tester', 'question title15', 'content15', 'English', 0, 'tester', now() - interval '9 day', 'tester', now() - interval '9 day'),
       ('tester', 'question title16', 'content16', 'English', 0, 'tester', now() - interval '8 day', 'tester', now() - interval '8 day'),
       ('tester', 'question title17', 'content17', 'IT', 0, 'tester', now() - interval '7 day', 'tester', now() - interval '7 day'),
       ('tester', 'question title18', 'content18', 'IT', 0, 'tester', now() - interval '6 day', 'tester', now() - interval '6 day'),
       ('tester', 'question title19', 'content19', 'IT', 0, 'tester', now() - interval '5 day', 'tester', now() - interval '5 day'),
       ('tester', 'question title20', 'content20', 'IT', 0, 'tester', now() - interval '4 day', 'tester', now() - interval '4 day'),
       ('tester', 'question title21', 'content21', 'IT', 0, 'tester', now() - interval '3 day', 'tester', now() - interval '3 day'),
       ('tester', 'question title22', 'content22', 'IT', 0, 'tester', now() - interval '2 day', 'tester', now() - interval '2 day'),
       ('tester', 'question title23', 'content23', 'IT', 0, 'tester', now() - interval '1 day', 'tester', now() - interval '1 day'),
       ('tester', 'question title24', 'content content content content content content content content content content content content', 'Free', 0, 'tester', now(), 'tester', now());
