name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: mrk19967/doubles
          stage: main
          yaml: >
            name: doubles

            app: java@21

            options:
              ports: 8080
              env:
                - name: DATABASE_HOST
                  value: 140.245.76.8:3306/doubles_db
                - name: DATABASE_USER
                  value: doubles
                - name: DATABASE_PASSWORD
                  value: doublespassword
                - name: REDIS_HOST
                  value: redis-18359.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
                - name: REDIS_PORT
                  value: "18359"
                - name: REDIS_PASSWORD
                  value: p444x6pVzg06HNGSyhSW1ofvH11xx993
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
